- menu_name: "Service"

- name: "Kontakt"
  url: "/kontakt/"
  class: "services-contact"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  class: "rss-link"
  title: "RSS abonnieren"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  class: "sitemap-link"
  title: "Sitemap für Google Webmastertools"
