- menu_name: "Service"

- name: "Kontakt"
  url: "/kontakt/"
  class: "services-contact"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  class: "rss-link"
  title: "RSS abonnieren"

- name: "Newsletter"
  url: "/newsletter/"
  class: "newsletter-link"
  title: "Kostenlos abonnieren, den Phlow Magazin Newsletter!"
