- menu_name: "Service"

- name: "Kontakt"
  url: "/kontakt/"
  class: "services-contact"
  title: "Contact"

- name: "Artikel RSS"
  url: "/feed.xml"
  class: "rss-link"
  title: "RSS abonnieren"

- name: "Blog RSS"
  url: "http://blog.phlow.de/rss"
  class: "rss-link"
  title: "RSS Feed vom Phlow Magazin Blog abonnieren"

- name: "Newsletter"
  url: "/newsletter/"
  class: "newsletter-link"
  title: "Kostenlos abonnieren, den Phlow Magazin Newsletter!"
